### PR TITLE
[#8771535]Prove that the evaluation is valid from ttm-math

### PR DESCRIPTION
**Pull request by ninjapanzer**
### What am I?

Fixes a index error when dealing with square root operations. All operations after the sq_root would fail
because the lookup indices would be off by three. This is the number of added expressions needed to complete the sq_root in literal expression {"root", 9, 2}

### QA

I am having issues writing tests for this because I think there might be a bug in the refinement associated with multiplication

### After merge
make a release for 0.3.2

### CODE REVIEW

**Comment by robwierzbowski** [comment]
Does this affect only calc? Looks good to me.

**Comment by joelmccracken** [comment]
example test looks good.

**Comment by ninjapanzer** [comment]
Its not. I got cornfused between the javascript-calculator and this

**Comment by joelmccracken** [comment]
Oh derp. Yeah, button pressing == calculator/eq builder specific

**Comment by robwierzbowski** [comment]
I can't remember if the square works the same way in eq builder as in the calc. If it does (it probably does) this is :+1:.

**Comment by ninjapanzer** [comment]
its a boondoggle

**Comment by ninjapanzer** [comment]
So this evaluation does work with ttm math on all operations

So this test just proves that and passes. Moving on the thinkthroughmath/javascript-calculator

**Comment by ninjapanzer** [comment]
This is ready to go it just proves the problem isn't here

**Comment by ninjapanzer** [comment]
test this please

**Comment by ninjapanzer** [comment]
test this please

**Comment by ninjapanzer** [comment]
test this please

**Comment by MandaBrown** [comment]
This looks good to me. :+1:

**Comment by carols10cents** [comment]
I'm stealing this CR from @seejee... I love these small, focused commits!!!! :heart: :heart: :heart: 

Is there anything for QA to do here or will they need to use javascript-calculator and/or lesson-player to be able to see a difference?

**Comment by ninjapanzer** [comment]
correct this can be merged anytime and no one will be the wiser

**Comment by carols10cents** [comment]
well then!

**Pull request merged**
